"""Tool-created disposable workspaces for Stage 0 output.

A workspace is where an analysis run publishes ``results.json`` and
``report.md``. It is created by :func:`create_workspace` beneath the operating
system's temporary directory; the CLI makes its own and there is no flag to
nominate one.

What the marker is, and is not
------------------------------
Each workspace carries a marker file recording what wrote it. **The marker is
not a capability, and this module does not treat it as one.** It lives inside
the very directory it describes, so it is self-authenticating: anyone able to
create a directory can equally create a matching marker, and a forged pair
verifies exactly like a genuine one. An earlier revision did call it a
capability and let it gate deletion - that claim was wrong, and the forgery was
demonstrated rather than merely argued.

The marker survives as a **sanity check**: it catches a stale path, a
half-created directory, or output aimed somewhere unintended. It is not a
security boundary, and nothing destructive depends on it. Deletion safety comes
from ``cleanup.py``, which accepts no caller-supplied path at all.

Nothing here is secure erasure, and nothing here should be pointed at real
participant data - see ``cleanup.py`` and plan §12.3.
"""

from __future__ import annotations

import json
import os
import secrets
import stat
import tempfile
from pathlib import Path
from typing import Any

MARKER_NAME = ".b18_stage0_workspace.json"
MARKER_TOOL = "scripts.b18_stage0"
MARKER_PURPOSE = "disposable synthetic Stage 0 workspace"
WORKSPACE_PREFIX = "b18_stage0_"
NONCE_BYTES = 16

REPO_ROOT = Path(__file__).resolve().parents[2]


class WorkspaceError(Exception):
    """A workspace could not be created, or failed its structural checks."""


def _is_reparse_point(path: Path) -> bool:
    """True for symlinks and, on Windows, junctions / other reparse points.

    ``Path.is_symlink()`` alone misses NTFS junctions, which redirect just as
    effectively.
    """
    try:
        info = path.lstat()
    except OSError:
        return False
    if stat.S_ISLNK(info.st_mode):
        return True
    attributes = getattr(info, "st_file_attributes", 0)
    return bool(attributes & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0))


def contains_reparse_point(root: Path) -> Path | None:
    """Return the first reparse point at or below ``root``, if any."""
    if _is_reparse_point(root):
        return root
    for current, directories, files in os.walk(root, followlinks=False):
        base = Path(current)
        for name in list(directories) + list(files):
            candidate = base / name
            if _is_reparse_point(candidate):
                return candidate
    return None


def system_temp_root() -> Path:
    return Path(tempfile.gettempdir()).resolve()


def create_workspace() -> Path:
    """Create a fresh disposable workspace and stamp it with a marker.

    The directory name is generated by :func:`tempfile.mkdtemp`, so two runs
    never collide and no caller-supplied string reaches the path.
    """
    root = system_temp_root()
    path = Path(tempfile.mkdtemp(prefix=WORKSPACE_PREFIX, dir=root)).resolve()
    marker = {
        "tool": MARKER_TOOL,
        "purpose": MARKER_PURPOSE,
        # A nonce, not a secret and not a capability: it distinguishes two
        # workspaces in a log. Nothing is authorized by knowing it.
        "nonce": secrets.token_hex(NONCE_BYTES),
        "contains": "synthetic Stage 0 analysis output only",
    }
    (path / MARKER_NAME).write_text(
        json.dumps(marker, indent=1, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    return path


def read_marker(path: Path) -> dict[str, Any]:
    """Load and check a workspace marker, or raise ``WorkspaceError``."""
    marker_path = path / MARKER_NAME
    if not marker_path.is_file():
        raise WorkspaceError(
            f"{path}: not a Stage 0 workspace - {MARKER_NAME} is missing. Only a "
            f"directory this tool created can be used."
        )
    if _is_reparse_point(marker_path):
        raise WorkspaceError(f"{marker_path}: marker is a link or reparse point")
    try:
        marker = json.loads(marker_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise WorkspaceError(f"{marker_path}: unreadable or malformed marker ({exc})") from exc

    if not isinstance(marker, dict):
        raise WorkspaceError(f"{marker_path}: marker must be a JSON object")
    if marker.get("tool") != MARKER_TOOL:
        raise WorkspaceError(f"{marker_path}: marker tool is {marker.get('tool')!r}, not {MARKER_TOOL!r}")
    if marker.get("purpose") != MARKER_PURPOSE:
        raise WorkspaceError(f"{marker_path}: marker purpose does not match")
    nonce = marker.get("nonce")
    if not (isinstance(nonce, str) and len(nonce) == NONCE_BYTES * 2):
        raise WorkspaceError(f"{marker_path}: marker nonce is missing or malformed")
    try:
        bytes.fromhex(nonce)
    except ValueError as exc:
        raise WorkspaceError(f"{marker_path}: marker nonce is not hex") from exc
    return marker


def verify_workspace(candidate: Path) -> Path:
    """Resolve and structurally check an output workspace.

    Checks where it lives, whether it carries this tool's naming and marker, and
    whether any part of it can redirect writes elsewhere. **This is a sanity
    check on an output destination, not an authorization check** - see the
    module docstring on why the marker cannot authenticate anything. Nothing
    destructive is gated on it.
    """
    if _is_reparse_point(candidate):
        raise WorkspaceError(f"{candidate}: refusing a symlink, junction or reparse point")

    resolved = candidate.resolve()
    temp_root = system_temp_root()

    if not resolved.is_absolute():
        raise WorkspaceError(f"{candidate}: refusing a non-absolute path")
    if not resolved.is_dir():
        raise WorkspaceError(f"{resolved}: not a directory")
    if resolved == temp_root or temp_root not in resolved.parents:
        raise WorkspaceError(
            f"{resolved}: a Stage 0 workspace must live beneath the system "
            f"temporary directory ({temp_root})"
        )
    if resolved == REPO_ROOT or REPO_ROOT in resolved.parents or resolved in REPO_ROOT.parents:
        raise WorkspaceError(f"{resolved}: refusing a path inside or containing the repository")
    if not resolved.name.startswith(WORKSPACE_PREFIX):
        raise WorkspaceError(
            f"{resolved}: directory name does not carry the {WORKSPACE_PREFIX!r} prefix "
            f"this tool assigns"
        )

    read_marker(resolved)   # sanity check, not an authorization check

    offender = contains_reparse_point(resolved)
    if offender is not None:
        raise WorkspaceError(
            f"{offender}: a symlink, junction or reparse point inside the workspace "
            f"could redirect writes or deletion outside it"
        )
    return resolved


def next_run_directory(workspace: Path) -> Path:
    """Allocate the next unused ``run-NNNN`` directory inside a workspace.

    Deterministic given the workspace's contents, and never reuses a name - so
    a completed run's artefacts can never be silently overwritten.
    """
    verified = verify_workspace(workspace)
    for index in range(1, 10_000):
        candidate = verified / f"run-{index:04d}"
        if not candidate.exists():
            return candidate
    raise WorkspaceError(f"{verified}: no free run directory (10000 already present)")
