"""Tool-created disposable workspaces for Stage 0 output.

An earlier revision let the caller nominate any directory as a "workspace" and
then write into, or delete, whatever was inside it. That is the wrong shape: it
made `Path.home()` a legal workspace root, which in turn made `AppData` and
`Documents` legal deletion targets.

The model here inverts that. A workspace is not something a caller *declares*;
it is something this module *creates*, beneath the operating system's temporary
directory, carrying a marker file with a capability token it generated. Output
and cleanup both require that marker to match. A directory the tool did not
create cannot be a workspace, however it is spelled on the command line.

Nothing here is secure erasure, and nothing here should be pointed at real
participant data - see `cleanup.py` and plan §12.3.
"""

from __future__ import annotations

import json
import os
import secrets
import stat
import tempfile
from pathlib import Path
from typing import Any

MARKER_NAME = ".b18_stage0_workspace.json"
MARKER_TOOL = "scripts.b18_stage0"
MARKER_PURPOSE = "disposable synthetic Stage 0 workspace"
WORKSPACE_PREFIX = "b18_stage0_"
CAPABILITY_BYTES = 16

REPO_ROOT = Path(__file__).resolve().parents[2]


class WorkspaceError(Exception):
    """A workspace could not be created, or failed capability verification."""


def _is_reparse_point(path: Path) -> bool:
    """True for symlinks and, on Windows, junctions / other reparse points.

    ``Path.is_symlink()`` alone misses NTFS junctions, which redirect just as
    effectively.
    """
    try:
        info = path.lstat()
    except OSError:
        return False
    if stat.S_ISLNK(info.st_mode):
        return True
    attributes = getattr(info, "st_file_attributes", 0)
    return bool(attributes & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0))


def contains_reparse_point(root: Path) -> Path | None:
    """Return the first reparse point at or below ``root``, if any."""
    if _is_reparse_point(root):
        return root
    for current, directories, files in os.walk(root, followlinks=False):
        base = Path(current)
        for name in list(directories) + list(files):
            candidate = base / name
            if _is_reparse_point(candidate):
                return candidate
    return None


def system_temp_root() -> Path:
    return Path(tempfile.gettempdir()).resolve()


def create_workspace() -> Path:
    """Create a fresh disposable workspace and stamp it with a capability.

    The directory name is generated by :func:`tempfile.mkdtemp`, so two runs
    never collide and no caller-supplied string reaches the path.
    """
    root = system_temp_root()
    path = Path(tempfile.mkdtemp(prefix=WORKSPACE_PREFIX, dir=root)).resolve()
    marker = {
        "tool": MARKER_TOOL,
        "purpose": MARKER_PURPOSE,
        "capability": secrets.token_hex(CAPABILITY_BYTES),
        "contains": "synthetic Stage 0 analysis output only",
    }
    (path / MARKER_NAME).write_text(
        json.dumps(marker, indent=1, sort_keys=True) + "\n", encoding="utf-8", newline="\n"
    )
    return path


def read_marker(path: Path) -> dict[str, Any]:
    """Load and check a workspace marker, or raise ``WorkspaceError``."""
    marker_path = path / MARKER_NAME
    if not marker_path.is_file():
        raise WorkspaceError(
            f"{path}: not a Stage 0 workspace - {MARKER_NAME} is missing. Only a "
            f"directory this tool created can be used."
        )
    if _is_reparse_point(marker_path):
        raise WorkspaceError(f"{marker_path}: marker is a link or reparse point")
    try:
        marker = json.loads(marker_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise WorkspaceError(f"{marker_path}: unreadable or malformed marker ({exc})") from exc

    if not isinstance(marker, dict):
        raise WorkspaceError(f"{marker_path}: marker must be a JSON object")
    if marker.get("tool") != MARKER_TOOL:
        raise WorkspaceError(f"{marker_path}: marker tool is {marker.get('tool')!r}, not {MARKER_TOOL!r}")
    if marker.get("purpose") != MARKER_PURPOSE:
        raise WorkspaceError(f"{marker_path}: marker purpose does not match")
    capability = marker.get("capability")
    if not (isinstance(capability, str) and len(capability) == CAPABILITY_BYTES * 2):
        raise WorkspaceError(f"{marker_path}: marker capability is missing or malformed")
    try:
        bytes.fromhex(capability)
    except ValueError as exc:
        raise WorkspaceError(f"{marker_path}: marker capability is not hex") from exc
    return marker


def verify_workspace(candidate: Path) -> Path:
    """Resolve and vet a workspace. Raises rather than guessing.

    Every check is structural: where it lives, what created it, and whether any
    part of it can redirect elsewhere.
    """
    if _is_reparse_point(candidate):
        raise WorkspaceError(f"{candidate}: refusing a symlink, junction or reparse point")

    resolved = candidate.resolve()
    temp_root = system_temp_root()

    if not resolved.is_absolute():
        raise WorkspaceError(f"{candidate}: refusing a non-absolute path")
    if not resolved.is_dir():
        raise WorkspaceError(f"{resolved}: not a directory")
    if resolved == temp_root or temp_root not in resolved.parents:
        raise WorkspaceError(
            f"{resolved}: a Stage 0 workspace must live beneath the system "
            f"temporary directory ({temp_root})"
        )
    if resolved == REPO_ROOT or REPO_ROOT in resolved.parents or resolved in REPO_ROOT.parents:
        raise WorkspaceError(f"{resolved}: refusing a path inside or containing the repository")
    if not resolved.name.startswith(WORKSPACE_PREFIX):
        raise WorkspaceError(
            f"{resolved}: directory name does not carry the {WORKSPACE_PREFIX!r} prefix "
            f"this tool assigns"
        )

    read_marker(resolved)   # capability check

    offender = contains_reparse_point(resolved)
    if offender is not None:
        raise WorkspaceError(
            f"{offender}: a symlink, junction or reparse point inside the workspace "
            f"could redirect writes or deletion outside it"
        )
    return resolved


def next_run_directory(workspace: Path) -> Path:
    """Allocate the next unused ``run-NNNN`` directory inside a workspace.

    Deterministic given the workspace's contents, and never reuses a name - so
    a completed run's artefacts can never be silently overwritten.
    """
    verified = verify_workspace(workspace)
    for index in range(1, 10_000):
        candidate = verified / f"run-{index:04d}"
        if not candidate.exists():
            return candidate
    raise WorkspaceError(f"{verified}: no free run directory (10000 already present)")
